### ISSUE TITLE
Manage your state like a boss in Angular

### ISSUE THREAD

**Issue by joaqcid** [gdgcordobaarg/TechTalks#1]
Te gustaria conocer nuevas tecnicas de state management? Queres conocer herramientas para poder llevarlo a cabo? O te interesa conocer los conceptos basicos de manejo de estado en una aplicacion? En este meetup con Joaquin Cid, hablaremos de algunas estrategias y enfoques para implementar state management en nuestras aplicaciones.

Joaquin nos va a contar acerca del "porque" de state management y algunos de los enfoques mas conocidos. Por ultima vamos a ver la libreria NGXS, y como nos puede ayudar a implementar facilmente state management en nuestras aplicaciones de Angular.

Bio
Joaquín Cid es fullstack developer en Toptal, con más de 12 años de experiencia en el desarrollo de software.

**Comment by joaqcid** [comment]
![image](https://user-images.githubusercontent.com/6530160/62213206-c7244080-b378-11e9-95a2-68c44ea5f99e.png)

**Comment by gdgcordobaarg** [comment]
Excelente presentación, los esperamos cuando quieran :)
Link del evento: https://www.meetup.com/GDG-CORDOBA-AR/events/263646560/
