### ISSUE TITLE
fix(TechTalk): GDG-005 - Improve bad experiences

### ISSUE THREAD

**Issue by mppastore** [gdgcordobaarg/TechTalks#2]
Sumate a esta charla a conocer un poco de que se trata el git flow, cuales son las espectativas a la hora de implementarlo, porque la gente lo usa y porque deberias implementarlo en tu proyecto si es que todavía no se hizo.

También vamos a sumar algunas experiencias para ver casos reales, las diferentas formas de trabajo tanto en equipos/empresas como en proyectos personales.
Que tan complicado es escalar un proyecto cuando el uso de git es poco convencional o no esta bien aceitado.

**Comment by gdgcordobaarg** [comment]
Excelente la charla Martin !
